/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
*/
// time complexity O(s+t), space complexity O(1)
class Solution {
    public char findTheDifference(String s, String t) {
        // we know ascii characters map to ints
        long sum1 = 0;
        long sum2 = 0;
        int diff = 0;
        // add the ascii sums of both strings and find the difference
        for(int i = 0;i<s.length();i++)
            sum1 = sum1 + s.charAt(i);
        for(int i = 0;i<t.length();i++)
            sum2 = sum2 + t.charAt(i);
        // the difference is the missing character
        diff = (int)(sum2 - sum1);
        return (char) diff;
    }
}